<a href="https://colab.research.google.com/github/ajitjain04/PRODIGY_DS_02/blob/main/TASK_2_INTERNSHIP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
url = 'https://github.com/m4gaikwad/PandasTutorial/raw/main/online_store_customer_data.csv'
data = pd.read_csv(url,on_bad_lines='skip')
data

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
0,1/1/2019,151200,Female,19.0,Single,Kansas,Basic,Unemployment,Other,1.0,2051.36
1,1/1/2019,151201,Male,49.0,Single,Illinois,Basic,self-employed,Card,0.0,544.04
2,1/1/2019,151202,Male,63.0,Married,New Mexico,Basic,workers,PayPal,1.0,1572.60
3,1/1/2019,151203,NaN,18.0,Single,Virginia,Platinum,workers,Card,1.0,1199.79
4,1/1/2019,151204,Male,27.0,Single,Connecticut,Basic,self-employed,Card,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2507,5/1/2021,153695,Female,57.0,Single,South Carolina,Platinum,self-employed,Card,0.0,150.10
2508,5/1/2021,153696,Female,36.0,Married,Hawaii,Silver,self-employed,PayPal,1.0,708.88
2509,5/1/2021,153697,Male,22.0,Single,South Carolina,Basic,workers,PayPal,1.0,2030.07
2510,5/1/2021,153698,NaN,44.0,Single,New York,Basic,Employees,PayPal,0.0,1909.77
2511,5/1/2021,153699,Male,48.0,Single,California,Silver,workers,PayPal,1.0,1073.15

In [ ]:
data.rename(columns={"Transactiond_Date" : 'Date',
'State_name ': 'State'},inplace ='True')

data.sample(5)

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
1864,9/18/2020,153052,Male,20.0,Single,Hawaii,Basic,self-employed,PayPal,1.0,1119.94
2230,1/30/2021,153418,Male,38.0,Single,Texas,Gold,workers,PayPal,1.0,2796.49
155,2/24/2019,151343,Male,16.0,Married,Oklahoma,Gold,Employees,Card,1.0,2497.12
1951,10/17/2020,153139,Female,47.0,Married,Maine,Basic,workers,PayPal,1.0,482.57
2163,1/4/2021,153351,Male,25.0,Married,Hawaii,Basic,workers,Card,1.0,2971.65

In [ ]:
data.duplicated().sum()

12

In [ ]:
data[data['State_names']== 'Kansas' ]

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
0,1/1/2019,151200,Female,19.0,Single,Kansas,Basic,Unemployment,Other,1.0,2051.36
60,1/26/2019,151260,Male,55.0,Married,Kansas,Basic,Employees,Other,1.0,1277.64
65,1/26/2019,151260,Male,55.0,Married,Kansas,Basic,Employees,Other,1.0,1277.64
100,2/6/2019,151295,Female,22.0,Married,Kansas,Missing,workers,Card,0.0,2061.14
126,2/12/2019,151314,Female,55.0,Married,Kansas,Platinum,Employees,PayPal,1.0,329.18
139,2/17/2019,151327,Female,77.0,Single,Kansas,Platinum,self-employed,PayPal,0.0,200.58
336,4/22/2019,151524,Male,70.0,Married,Kansas,Basic,self-employed,PayPal,0.0,492.40
368,5/3/2019,151556,Male,70.0,Single,Kansas,Basic,Employees,Other,1.0,1559.00
468,6/3/2019,151656,Female,49.0,Single,Kansas,Basic,Unemployment,Card,NaN,1057.45
521,6/20/2019,151709,Female,76.0,Single,Kansas,Silver,Employees,PayPal,1.0,82.27
558,6/30/2019,151746,Male,48.0,Married,Kansas,Basic,workers,Card,1.0,1062.23
569,7/4/2019,151757,Female,20.0,Single,Kansas,Platinum,self-employed,PayPal,0.0,NaN
572,7/5/2019,151760,Female,61.0,Married,Kansas,Basic,self-employed,Other,1.0,1699.31
690,8/14/2019,151878,Female,31.0,Single,Kansas,Platinum,self-employed,PayPal,0.0,875.04
739,8/28/2019,151927,Female,39.0,Married,Kansas,Basic,Employees,PayPal,0.0,NaN
888,10/16/2019,152076,Male,36.0,Single,Kansas,Basic,Unemployment,Card,0.0,2744.96
1015,12/1/2019,152203,Male,48.0,Married,Kansas,Basic,Employees,PayPal,1.0,1015.45
1244,2/11/2020,152432,Male,50.0,Married,Kansas,Basic,workers,Other,1.0,NaN
1309,3/5/2020,152497,Male,61.0,Married,Kansas,Basic,NaN,Card,1.0,126.08
1375,3/31/2020,152563,Male,45.0,Married,Kansas,Basic,workers,Card,1.0,2534.05
1413,4/14/2020,152601,Male,74.0,Married,Kansas,Platinum,self-employed,Other,0.0,473.24
1478,5/11/2020,152666,Male,42.0,Single,Kansas,Silver,self-employed,PayPal,1.0,1763.71
1530,5/28/2020,152718,Female,28.0,Married,Kansas,Silver,workers,PayPal,NaN,1031.86
1560,6/7/2020,152748,Female,67.0,Married,Kansas,Platinum,workers,Other,0.0,524.88
1630,7/4/2020,152818,Female,51.0,Married,Kansas,Platinum,workers,PayPal,1.0,1242.69
1715,8/7/2020,152903,Male,42.0,Single,Kansas,Basic,Unemployment,PayPal,1.0,611.85
1769,8/19/2020,152957,Male,30.0,Single,Kansas,Basic,self-employed,Card,NaN,1452.53
1772,8/21/2020,152960,Female,46.0,Married,Kansas,Basic,Employees,Card,1.0,NaN
1787,8/26/2020,152975,Female,18.0,Single,Kansas,Silver,Employees,PayPal,0.0,2540.03
1889,9/25/2020,153077,Male,16.0,Married,Kansas,Missing,self-employed,Card,1.0,1974.17
1959,10/19/2020,153147,Female,16.0,Single,Kansas,Basic,self-employed,Card,0.0,1479.99
2002,11/4/2020,153190,Female,55.0,Single,Kansas,Basic,Employees,PayPal,0.0,299.81
2048,11/22/2020,153236,Male,45.0,Single,Kansas,Platinum,Employees,Card,1.0,1407.18
2074,11/30/2020,153262,Male,46.0,Single,Kansas,Missing,Employees,Card,1.0,584.71
2086,12/7/2020,153274,Female,33.0,Married,Kansas,Basic,Unemployment,Other,0.0,1639.64
2099,12/10/2020,153287,Male,25.0,Single,Kansas,Basic,Employees,Other,1.0,NaN
2117,12/18/2020,153305,Male,71.0,Single,Kansas,Silver,workers,PayPal,1.0,1736.68
2179,1/9/2021,153367,Female,32.0,Married,Kansas,Missing,Employees,Card,0.0,464.15
2297,2/21/2021,153485,Female,46.0,Married,Kansas,Platinum,workers,PayPal,0.0,2025.00
2452,4/13/2021,153640,Male,51.0,Married,Kansas,Basic,Employees,PayPal,0.0,820.66
2461,4/15/2021,153649,Male,15.0,Single,Kansas,Basic,workers,PayPal,1.0,2901.98

In [ ]:
data[(data['Age'] >= 45) & (data['Age']<= 60)]

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
1,1/1/2019,151201,Male,49.0,Single,Illinois,Basic,self-employed,Card,0.0,544.04
10,1/4/2019,151210,Female,56.0,Married,California,Basic,Employees,PayPal,0.0,1712.82
12,1/5/2019,151212,Female,60.0,Married,Iowa,Basic,self-employed,Card,1.0,819.08
13,1/5/2019,151213,Male,47.0,Single,South Carolina,Basic,Employees,PayPal,1.0,1719.83
19,1/8/2019,151219,Female,46.0,Married,Missouri,Basic,Employees,Card,1.0,2968.95
...,...,...,...,...,...,...,...,...,...,...,...
2494,4/27/2021,153682,Male,56.0,Married,Wisconsin,Basic,workers,PayPal,1.0,1888.91
2498,4/28/2021,153686,Female,55.0,Single,Ohio,Silver,Unemployment,PayPal,0.0,1553.61
2505,4/30/2021,153693,Male,54.0,Married,Alabama,Basic,Employees,Card,0.0,266.61
2507,5/1/2021,153695,Female,57.0,Single,South Carolina,Platinum,self-employed,Card,0.0,150.10
2511,5/1/2021,153699,Male,48.0,Single,California,Silver,workers,PayPal,1.0,1073.15

In [ ]:
data[(data['Age'] >= 45) & (data['Age']<= 60) & (data['Marital_status'] == "Single" )& (data["Gender"] == 'Male')]

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent
1,1/1/2019,151201,Male,49.0,Single,Illinois,Basic,self-employed,Card,0.0,544.04
13,1/5/2019,151213,Male,47.0,Single,South Carolina,Basic,Employees,PayPal,1.0,1719.83
23,1/9/2019,151223,Male,47.0,Single,Nebraska,Basic,self-employed,PayPal,1.0,2407.36
51,1/22/2019,151251,Male,56.0,Single,Louisiana,Basic,self-employed,Card,0.0,2445.03
53,1/23/2019,151253,Male,51.0,Single,Kentucky,Basic,self-employed,PayPal,1.0,1312.78
...,...,...,...,...,...,...,...,...,...,...,...
2392,3/23/2021,153580,Male,46.0,Single,West Virginia,Basic,workers,PayPal,1.0,1327.68
2427,4/5/2021,153615,Male,49.0,Single,Massachusetts,Platinum,Employees,Other,1.0,1219.29
2433,4/6/2021,153621,Male,53.0,Single,Louisiana,Silver,workers,Card,1.0,173.57
2453,4/13/2021,153641,Male,52.0,Single,Connecticut,Silver,workers,Card,1.0,334.58
2511,5/1/2021,153699,Male,48.0,Single,California,Silver,workers,PayPal,1.0,1073.15

In [ ]:
df = data.dropna(subset = ['Age'])

In [ ]:
df['Age_Range'] = np.where(df['Age'] <= 30,'Young',
np.where(df['Age']<= 45,'Middle',
'old'))
df['Age_Range']

df.head(5)

<ipython-input-13-67dd9573ece0>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age_Range'] = np.where(df['Age'] <= 30,'Young',

,Transaction_date,Transaction_ID,Gender,Age,Marital_status,State_names,Segment,Employees_status,Payment_method,Referal,Amount_spent,Age_Range
0,1/1/2019,151200,Female,19.0,Single,Kansas,Basic,Unemployment,Other,1.0,2051.36,Young
1,1/1/2019,151201,Male,49.0,Single,Illinois,Basic,self-employed,Card,0.0,544.04,old
2,1/1/2019,151202,Male,63.0,Married,New Mexico,Basic,workers,PayPal,1.0,1572.60,old
3,1/1/2019,151203,NaN,18.0,Single,Virginia,Platinum,workers,Card,1.0,1199.79,Young
4,1/1/2019,151204,Male,27.0,Single,Connecticut,Basic,self-employed,Card,0.0,NaN,Young

In [ ]:
df.groupby('Age_Range')['Age'].count()

Age_Range
Middle     601
Young      580
old       1289
Name: Age, dtype: int64